WHITESPACE = { " " | "\t" | "\r" | "\n" }

top = { SOI ~ string ~ EOI }

string = { anchor_start? ~ quoted_string ~ anchor_end?}

quoted_string = ${ PUSH("'" | "\"") ~ quoted_char* ~ POP }

quoted_char = ${
 ! (PEEK | "\\") ~ literal_char
 | ("\\" ~ (escaped_char | "u{" ~ unicode_seq ~ "}"))
}

anchor_start = @{ "^" }

anchor_end = @{ "$" }

literal_char = @{ ANY }

escaped_char = @{("\"" | "'" | "`" | "\\" | "n" | "r" | "t"  )}

unicode_seq = @{ ASCII_HEX_DIGIT{1,6} }