#!/bin/bash

while IFS= read -r line; do
  echo "$line"
  exit_code=1
done < <(
  cargo "$@" --message-format json |
  jq -r '
    select(.message.level and (.message.spans | length > 0)) 
    | {level: (.message.level | sub("note"; "notice")), message: .message.message} as $ctx
    | .message.spans[] 
    | "::\($ctx.level) line=\(.line_start),col=\(.column_start),endLine=\(.line_end),columnEnd=\(.column_end),title=rust check::\($ctx.message)"'
)

exit "$exit_code"
