name: Post-release
on:
  push:
    branches: [ "main" ]
    paths:
      - Cargo.toml

jobs:
  bump_version:
    if: ${{ startsWith(github.ref, 'pending-releases/') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'releases/'. TODO!"
